name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: ap-south-1

jobs:

  destroy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy DEV
        if: github.event.inputs.environment == 'dev'
        run: | 
          terraform workspace select dev || terraform workspace new dev
          terraform destroy -auto-approve -var-file="environments/dev.tfvars"

      - name: Terraform Destroy PROD
        if: github.event.inputs.environment == 'prod'
        run: | 
          terraform workspace select prod || terraform workspace new prod
          terraform destroy -auto-approve -var-file="environments/prod.tfvars"